// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package transfer

import (
	"context"
	"github.com/patriciapedrosaa/transfer-me/app/domain/entities"
	"sync"
)

// Ensure, that UseCaseMock does implement UseCase.
// If this is not the case, regenerate this file with moq.
var _ UseCase = &UseCaseMock{}

// UseCaseMock is a mock implementation of UseCase.
//
// 	func TestSomethingThatUsesUseCase(t *testing.T) {
//
// 		// make and configure a mocked UseCase
// 		mockedUseCase := &UseCaseMock{
// 			CreateFunc: func(ctx context.Context, input CreateTransferInput) (entities.Transfer, error) {
// 				panic("mock out the Create method")
// 			},
// 			GetTransfersByAccountIDFunc: func(ctx context.Context, accountID string) ([]entities.Transfer, error) {
// 				panic("mock out the GetTransfersByAccountID method")
// 			},
// 		}
//
// 		// use mockedUseCase in code that requires UseCase
// 		// and then make assertions.
//
// 	}
type UseCaseMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, input CreateTransferInput) (entities.Transfer, error)

	// GetTransfersByAccountIDFunc mocks the GetTransfersByAccountID method.
	GetTransfersByAccountIDFunc func(ctx context.Context, accountID string) ([]entities.Transfer, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input CreateTransferInput
		}
		// GetTransfersByAccountID holds details about calls to the GetTransfersByAccountID method.
		GetTransfersByAccountID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
		}
	}
	lockCreate                  sync.RWMutex
	lockGetTransfersByAccountID sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UseCaseMock) Create(ctx context.Context, input CreateTransferInput) (entities.Transfer, error) {
	callInfo := struct {
		Ctx   context.Context
		Input CreateTransferInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			transferOut entities.Transfer
			errOut      error
		)
		return transferOut, errOut
	}
	return mock.CreateFunc(ctx, input)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedUseCase.CreateCalls())
func (mock *UseCaseMock) CreateCalls() []struct {
	Ctx   context.Context
	Input CreateTransferInput
} {
	var calls []struct {
		Ctx   context.Context
		Input CreateTransferInput
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetTransfersByAccountID calls GetTransfersByAccountIDFunc.
func (mock *UseCaseMock) GetTransfersByAccountID(ctx context.Context, accountID string) ([]entities.Transfer, error) {
	callInfo := struct {
		Ctx       context.Context
		AccountID string
	}{
		Ctx:       ctx,
		AccountID: accountID,
	}
	mock.lockGetTransfersByAccountID.Lock()
	mock.calls.GetTransfersByAccountID = append(mock.calls.GetTransfersByAccountID, callInfo)
	mock.lockGetTransfersByAccountID.Unlock()
	if mock.GetTransfersByAccountIDFunc == nil {
		var (
			transfersOut []entities.Transfer
			errOut       error
		)
		return transfersOut, errOut
	}
	return mock.GetTransfersByAccountIDFunc(ctx, accountID)
}

// GetTransfersByAccountIDCalls gets all the calls that were made to GetTransfersByAccountID.
// Check the length with:
//     len(mockedUseCase.GetTransfersByAccountIDCalls())
func (mock *UseCaseMock) GetTransfersByAccountIDCalls() []struct {
	Ctx       context.Context
	AccountID string
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
	}
	mock.lockGetTransfersByAccountID.RLock()
	calls = mock.calls.GetTransfersByAccountID
	mock.lockGetTransfersByAccountID.RUnlock()
	return calls
}
